/**:
  ros__parameters:
    robot_base_frame: base_link
    return_to_init: false
    costmap_topic: map
    costmap_updates_topic: map_updates
    visualize: true
    planner_frequency: 0.05
    progress_timeout: 300.0
    potential_scale: 3.0
    orientation_scale: 0.0
    gain_scale: 1.0
    transform_tolerance: 0.5
    min_frontier_size: 1.0
    
    # Map saving parameters
    enable_map_saving: false
    map_save_path: "/home/ztl/slam_data/map"
    map_save_format: "png"