lio_sam:
  # Topics
  pointCloudTopic: "livox/lidar"               # Point cloud data
  imuTopic: "livox/imu"                      # IMU data
  odomTopic: "odometry/imu"                  # IMU pre-preintegration odometry, same frequency as IMU
  gpsTopic: "odometry/gps"                   # GPS odometry topic from navsat, see navsat.launch file

  # Frames
  lidarFrame: "base_link"
  baselinkFrame: "base_link"
  odometryFrame: "odom"
  mapFrame: "map"

  # GPS Settings
  useImuHeadingInitialization: false
  useGpsElevation: false
  gpsCovThreshold: 2.0
  poseCovThreshold: 25.0

  # Save pcd
  savePCD: false
  savePCDDirectory: "/Downloads/LOAM/"

  # Sensor Settings
  sensor: livox                              # Options: velodyne, ouster, livox
  N_SCAN: 6                                 # Number of lidar channel (i.e., Velodyne/Ouster: 16, 32, 64, 128, Livox Horizon: 6)
  Horizon_SCAN: 4000                        # Horizon scan resolution (Velodyne:1800, Ouster:512,1024,2048, Livox Horizon: 4000)
  downsampleRate: 1                         # Downsample rate, skip downsampleRate-1 clouds, default=1
  lidarMinRange: 0.5                        # Minimum range of lidar, default=0.5
  lidarMaxRange: 1000.0                     # Maximum range of lidar, default=1000.0

  # IMU Settings
  # IMU data is required for LIO-SAM. For Ouster users, please enable the imu in the driver
  # and set the imu topic in the launch file. For other lidar users, please provide 9-axis IMU data.
  imuAccNoise: 3.9939570888238808e-03
  imuGyrNoise: 1.5636343949698187e-03
  imuAccBiasN: 6.4356659353532566e-05
  imuGyrBiasN: 3.5640318696367613e-05
  imuGravity: 9.80511
  imuRPYWeight: 0.01

  # Extrinsics (lidar -> IMU)
  extrinsicTrans: [0.0, 0.0, 0.0]
  extrinsicRot: [-1, 0, 0,
                  0, 1, 0,
                  0, 0, -1]
  extrinsicRPY: [0, -1, 0,
                  1, 0, 0,
                  0, 0, 1]

  # LOAM feature threshold
  edgeThreshold: 1.0
  surfThreshold: 0.1
  edgeFeatureMinValidNum: 10
  surfFeatureMinValidNum: 100

  # voxel filter paprams
  odometrySurfLeafSize: 0.4                      # default: 0.4 - for odometry
  mappingCornerLeafSize: 0.2                     # default: 0.2 - for mapping
  mappingSurfLeafSize: 0.4                      # default: 0.4 - for mapping

  # robot motion constraint (in case you are using a 2D robot)
  z_tollerance: 1000.0                            # meters
  rotation_tollerance: 1000.0                    # radians

  # CPU Params
  numberOfCores: 4                                # number of cores for mapping optimization
  mappingProcessInterval: 0.15                    # seconds, regulate mapping frequency

  # Surrounding map
  surroundingkeyframeAddingDistThreshold: 1.0      # meters, regulate keyframe adding threshold
  surroundingkeyframeAddingAngleThreshold: 0.2    # radians, regulate keyframe adding threshold
  surroundingKeyframeDensity: 2.0                 # meters, downsample surrounding keyframe poses
  surroundingKeyframeSearchRadius: 50.0            # meters, within n meters scan-to-map optimization (when loop closure disabled)

  # Loop closure
  loopClosureEnableFlag: true
  loopClosureFrequency: 1.0                        # Hz, regulate loop closure constraint add frequency
  surroundingKeyframeSize: 50                      # submap size (when loop closure enabled)
  historyKeyframeSearchRadius: 15.0                 # meters, key frame that is n meters far from current frame will be considered for loop closure
  historyKeyframeSearchTimeDiff: 30.0              # seconds, key frame that is n seconds older will be considered for loop closure
  historyKeyframeSearchNum: 25                     # number of hostory key frames around loop closure frame
  historyKeyframeFitnessScore: 0.3                 # icp threshold, the smaller the better alignment

  # Global map visualization radius
  globalMapVisualizationSearchRadius: 1000.0       # meters, global map visualization radius
  globalMapVisualizationPoseDensity: 10.0          # meters, global map visualization keyframe density
  globalMapVisualizationLeafSize: 1.0              # meters, global map visualization cloud density