/**:
  ros__parameters:
    robot_base_frame: base_link
    return_to_init: false
    costmap_topic: map
    costmap_updates_topic: map_updates
    visualize: false
    planner_frequency: 0.05
    progress_timeout: 60.0
    potential_scale: 3.0
    orientation_scale: 0.0
    gain_scale: 1.0
    transform_tolerance: 0.5
    min_frontier_size: 0.2