/**:
  ros__parameters:
    lio.map.save_map: false
    lio.map.if_filter: true
    lio.map.save_map_dir: "map"
    lio.map.map_name: "map.pcd"
    lio.map.ds_size: 0.3
    lio.map.save_interval: 500

    lio.ros.lidar_topic: "/livox/lidar"
    lio.ros.imu_topic: "/livox/imu"

    lio.sensor.lidar_type: 1
    lio.sensor.blind: 0.3
    lio.sensor.maxrange: 100.0
    lio.sensor.filter_rate: 3.0
    lio.sensor.enable_downsample: true
    lio.sensor.voxel_fliter_size: 0.5
    lio.sensor.gravity_norm: 9.7946
    lio.sensor.imu_type: 1
    lio.sensor.imu_na: 0.1
    lio.sensor.imu_ng: 0.1
    lio.sensor.imu_nba: 0.0001
    lio.sensor.nbg: 0.0001

    lio.extrinsic.lidar_imu: [-0.011, -0.02329, 0.04412, 
                              1.0, 0.0, 0.0, 
                              0.0, 1.0, 0.0, 
                              0.0, 0.0, 1.0]
    lio.extrinsic.odom_robo: [0.0, 0.0, 0.13, 0.0, 0.0, 0.0]

    lio.hash_map.hash_capacity: 100000000
    lio.hash_map.vox_resolution: 0.5
    lio.hash_map.insert_resolution: 0.5

    lio.kf.kf_type: 0
    lio.kf.kf_max_iterations: 4
    lio.kf.kf_align_gravity: true
    lio.kf.kf_quit_eps: 0.001

    lio.submap.submap_resolution: 0.5
    lio.submap.submap_capacity: 1000000

    lio.output.robot: false
    lio.output.plan_env_world: false
    lio.output.plan_env_body: false
    lio.output.ml_map: false
    lio.output.planner: false
    lio.output.map: true
    lio.output.dense: true
    lio.output.pub_step: 1

    lio.relocation.update_map: true
    lio.relocation.init_pose: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    lio.eva.timer: true