laserMapping:
  ros__parameters:
    common:
      lid_topic: "/livox/lidar"
      imu_topic: "/livox/imu"
      con_frame: false # true: if you need to combine several LiDAR frames into one
      con_frame_num: 1 # the number of frames combined
      cut_frame: false # true: if you need to cut one LiDAR frame into several subframes
      cut_frame_time_interval: 0.1 # should be integral fraction of 1 / LiDAR frequency
      time_diff_lidar_to_imu: 0.0 # Time offset between LiDAR and IMU calibrated by other algorithms, e.g., LI-Init (find in Readme)

    preprocess:
      lidar_type: 1 # 4
      scan_line: 6 # 32
      timestamp_unit: 1           # the unit of time/t field in the PointCloud2 rostopic: 0-second, 1-milisecond, 2-microsecond, 3-nanosecond.
      blind: 0.5

    mapping:
      imu_en: true
      extrinsic_est_en: false # for aggressive motion, set this variable false
      imu_time_inte: 0.005 # = 1 / frequency of IMU
      lidar_time_inte: 0.1
      satu_acc: 3.0 # the saturation value of IMU's acceleration. not related to the units
      satu_gyro: 35 # the saturation value of IMU's angular velocity. not related to the units
      acc_norm: 1.0 # 9.810 # 1.0 for g as unit, 9.81 for m/s^2 as unit of the IMU's acceleration
      lidar_meas_cov: 0.01 # 0.001; 0.01
      acc_cov_output: 500
      gyr_cov_output: 1000
      b_acc_cov: 0.0001
      b_gyr_cov: 0.0001
      imu_meas_acc_cov: 0.1 #0.1 # 0.1
      imu_meas_omg_cov: 0.1 #0.01 # 0.1