common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/livox/imu"
    time_sync_en: false
    time_offset_lidar_to_imu: 0.0
    gravity_constant: 9.8066

preprocess:
    lidar_type: 5  # MID360
    scan_line:  4
    blind: 0.3
    timestamp_unit: 3
    scan_rate: 10

mapping:
    acc_cov: 0.2
    gyr_cov: 0.2
    b_acc_cov: 0.01
    b_gyr_cov: 0.01
    fov_degree:    360.0
    det_range:     60.0
    extrinsic_est_en:  false
    # MID360 extrinsic parameters
    extrinsic_T: [ -0.011, -0.02329, 0.04412 ]
    extrinsic_R: [ 1., 0., 0.,
                    0., 1., 0.,
                    0., 0., 1.]

publish:
    path_en: true
    effect_map_en: false
    map_en: true
    scan_publish_en:  true
    dense_publish_en: true
    scan_bodyframe_pub_en: true

pcd_save:
    pcd_save_en: true
    interval: 5